AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  devices-location

  Sample SAM Template for devices-location

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  DevicesLocationFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: DevicesLocationFunction
      Handler: dl.App::handleRequest
      Runtime: java11
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        ReadAllDevices:
          Type: Api
          Properties:
            Path: /devices
            Method: get
        ReadDeviceById:
          Type: Api
          Properties:
            Path: /devices/{id}
            Method: get
        CreateDevice:
          Type: Api
          Properties:
            Path: /devices
            Method: post
        UpdateDevice:
          Type: Api
          Properties:
            Path: /devices/{id}
            Method: put
        DeleteDevice:
          Type: Api
          Properties:
            Path: /devices/{id}
            Method: delete

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DevicesLocationApi:
    Description: "API Gateway endpoint URL for Prod stage for Devices Location function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/dl/"
  DevicesLocationFunction:
    Description: "Devices Location Lambda Function ARN"
    Value: !GetAtt DevicesLocationFunction.Arn
  DevicesLocationFunctionIamRole:
    Description: "Implicit IAM Role created for Devices Location function"
    Value: !GetAtt DevicesLocationFunctionRole.Arn
